---drop all Tables from NerdAirways---

DROP TABLE  aw_review CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_booking CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_luggage CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_class CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_flight CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_flightstatus CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_terminal CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_country CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_creditcard CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_customer CASCADE CONSTRAINTS PURGE;
DROP TABLE  aw_article CASCADE CONSTRAINTS PURGE;